//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinksSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_MemberRechargeRecord
    {
        public int memberRechargeID { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<decimal> rechargeAmount { get; set; }
        public Nullable<decimal> promotionalAmount { get; set; }
        public Nullable<decimal> promotionalIntegral { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public string remark { get; set; }
    }
}
