//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinksSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrinksSystemEntities : DbContext
    {
        public DrinksSystemEntities()
            : base("name=DrinksSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_Handover> B_Handover { get; set; }
        public virtual DbSet<B_MemberRechargeRecord> B_MemberRechargeRecord { get; set; }
        public virtual DbSet<B_SalesRecord> B_SalesRecord { get; set; }
        public virtual DbSet<B_SalesRecordDetails> B_SalesRecordDetails { get; set; }
        public virtual DbSet<S_Dictionary> S_Dictionary { get; set; }
        public virtual DbSet<S_Member> S_Member { get; set; }
        public virtual DbSet<S_Product> S_Product { get; set; }
        public virtual DbSet<S_Staff> S_Staff { get; set; }
    }
}
