//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinksSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productNumber { get; set; }
        public Nullable<int> productTypeID { get; set; }
        public Nullable<int> cupTypeID { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<decimal> productCost { get; set; }
        public Nullable<decimal> memberPrice { get; set; }
        public Nullable<decimal> productIntegral { get; set; }
        public byte[] productImage { get; set; }
    }
}
